server:
  port: 8081

spring:
  application:
    name: shop-service
  jpa:
    open-in-view: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_service_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
